FROM python:3.12.8-slim-bullseye

WORKDIR /website

COPY /website /website

RUN apt-get update && \
    apt-get upgrade -y && \
    chmod +x /website/entrypoint.sh

# Install requirements with pip cache for efficiency
RUN --mount=type=cache,target=/root/.cache/pip pip install --no-cache-dir -r /website/requirements.txt

EXPOSE 5000

CMD ["/website/entrypoint.sh"]